### ISSUE TITLE
#define offsetof(TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)  = compile error

### ISSUE THREAD

**Issue by Zwilla** [bitmaintech/S9_firmware#4]
use this:

#undef offsetof
#define offsetof(TYPE, MEMBER) ((size_t) &((TYPE *)0)->MEMBER)
#define SIZEOF(TYPE, MEMBER) (sizeof(((TYPE *)0)->MEMBER))

**Comment by Fazio** [comment]
Thanks for your comments, I will commit the clean up code
